TIBCOSoftware/mashling

cli/app/api_test.go, ext/flogo/trigger/gorillamuxtrigger/trigger_test.go
=> Chore gotest fix

cli/app/api.go, cli/app/files.go, cli/app/restore_dependency_test.go, cli/app/util.go, cli/app/validate_test.go, cli/env/env.go, cli/env/gb.go
=> Recipe dep

ext/flogo/trigger/gorillamuxtrigger/README.md, ext/flogo/trigger/gorillamuxtrigger/auth.go, ext/flogo/trigger/gorillamuxtrigger/auth_test.go, ext/flogo/trigger/gorillamuxtrigger/trigger.go, ext/flogo/trigger/gorillamuxtrigger/trigger.json
* Lookup users to authenticate in a file
=> Added ability to perform basic auth against the gw

cli/app/create.go, cli/app/list.go, cli/app/validate.go, cli/app/version.go
* It was showing a mixture of uppercase and lowercase for the first
character.
=> Fix 'mashling help' screen's formatting issue

cli/app/api.go, cli/app/api_test.go, cli/app/build.go, cli/app/consul_api_test.go, cli/app/create.go, cli/app/files.go, cli/app/samples_test.go, cli/app/util.go, cli/app/version.go, cli/docs/gateway.md, ext/flogo/activity/ping/README.md, ext/flogo/activity/ping/activity.go, ext/flogo/activity/ping/activity.json, ext/flogo/activity/ping/activity_test.go, lib/flow/pingflow.json, lib/flow/pingflowdetailed.json, lib/model/model.go, lib/util/consts.go, lib/util/util.go
=> Updated ping functionality

lib/flow/KafkaTriggerToRestActivity.json, lib/flow/RestTriggerToRestGetActivity.json, lib/flow/RestTriggerToRestPutActivity.json
=> Feature chore cleanup

Makefile, README.md, cli/README.md
=> Readme dep

lib/flow/TunableRestInvokerPost.json
=> Added tunable post flow for push notification recipe

lib/util/util.go
=> use github raw content for getting github files

internal/pkg/model/v1/translate.go
=> Added tunable fix

cli/assets/defGopkg.lock, cli/samples/kafka-conditional-gateway/Gopkg.lock, cli/samples/rest-conditional-gateway/Gopkg.lock, cli/samples/secure-rest-gateway/Gopkg.lock
=> Updated lock files

internal/app/cli/command/create.go
This PR creates a single docker container and execs all commands through that when building customized mashling gateway binaries using Docker. It also no longer mounts a host volume and just copies code into the container once and out of the container once.
=> Improve 'create' process for mashling-cli when using Docker.

internal/pkg/model/v1/gateway.go
=> Added port mapping for v1 recipes

internal/app/cli/command/create.go
Please review and accept this PR.
=> issue fix 172 - copy exe into bin folder

internal/app/cli/command/create.go
Please review and Accept this PR.
=> Reverted issue 172

docs/gateway/README.md
Docs now contain request inputs and response outputs for each service type.
=> Expanded docs for service types.

ext/flogo/trigger/gorillamuxtrigger/trigger_test.go, lib/util/util_test.go
Please review and accept this PR.
=> Fixed gotests

docs/cli/README.md, docs/gateway/README.md, docs/web/content/getting-started/gateway.md, docs/web/content/getting-started/getting-started-cli/_index.md, internal/app/cli/command/command.go, internal/app/gateway/command/run.go
Please review and accept this PR.
=> Fix type mistakes in read me content

.travis.yml, docs/web/content/development/developing-from-source.md, docs/web/content/getting-started/gateway.md, docs/web/content/getting-started/getting-started-cli/_index.md
Removed/corrected feature-v2-model branch references.
=> Remove feature-v2-model branch references

vendor/github.com/TIBCOSoftware/flogo-contrib/action/flow/action.go
Please review and accept this PR.
=> Added 1 nano second delay while creating resourse in action

build.go
noasm is not needed with amd64
=> Only use noasm with arm
